//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;


public class GJDepthFirst<R,A> implements GJVisitor<R,A> {

   
   public LinkedHashMap<String, ClassInfo> symbolTable = new LinkedHashMap<>();

   
   private String currentClassName = null;
   private String currentMethodName = null;

    private MethodInfo lookupMethodInHierarchy(String className, String methodName) {
        String currentClassName = className;

        
        while (currentClassName != null) {
            ClassInfo classInfo = this.symbolTable.get(currentClassName);

            if (classInfo == null) {
                return null; 
            }

            
            if (classInfo.methods.containsKey(methodName)) {
                return classInfo.methods.get(methodName);
            }

            
            currentClassName = classInfo.parent;
        }

        return null;
    }

   
   public void printSymbolTable() {
       System.out.println("--- Symbol Table ---");
       for (Map.Entry<String, ClassInfo> entry : symbolTable.entrySet()) {
           System.out.println("Class: " + entry.getKey());
           System.out.println(entry.getValue());
          
           System.out.println("parent class");
           System.out.println(entry.getValue().parent);
             System.out.println("Variables and their types:");
               for(Map.Entry<String, String> var_entry : entry.getValue().var_types.entrySet())
               {
                  System.out.println("  " + var_entry.getKey() + " : " + var_entry.getValue());
               }
           System.out.println("--------------------");
       }
      
   }

   
   public void fill_var_types()
   {
      for(String className : symbolTable.keySet())
      {
         ClassInfo classInfo = symbolTable.get(className);
         classInfo.fillvar_types();
      }
   }


   public R visit(NodeList n, A argu) {
      R _ret=null;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return (R)n.tokenImage; }



   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return null;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      return null;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      
      this.currentClassName = (String) n.f1.accept(this, argu);
      ClassInfo mainClassInfo = new ClassInfo();
      
     
      MethodInfo mainMethodInfo = new MethodInfo();
      mainMethodInfo.returnType = "void";
      String paramName = (String) n.f11.accept(this, argu);
      mainMethodInfo.addParameter(paramName, "String[]");
      
      mainClassInfo.addMethod("main", mainMethodInfo);
      this.symbolTable.put(this.currentClassName, mainClassInfo);

      
      this.currentClassName = null;
      return null;
   }

   /**
    * f0 -> ClassDeclaration()
    * | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      n.f0.accept(this, argu);
      return null;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      this.currentClassName = (String) n.f1.accept(this, argu);

      if (this.symbolTable.containsKey(this.currentClassName)) {
          System.out.println("Type error");
          this.currentClassName = null; 
          return null;
      }

      this.symbolTable.put(this.currentClassName, new ClassInfo());
      
      n.f3.accept(this, argu); 
      n.f4.accept(this, argu);
      
      this.currentClassName = null; 
      return null;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      this.currentClassName = (String) n.f1.accept(this, argu);
      String parentName = (String) n.f3.accept(this, argu);

      if (this.symbolTable.containsKey(this.currentClassName)) {
          System.out.println("Type error");
          this.currentClassName = null;
          return null;
      }
      
      ClassInfo classInfo = new ClassInfo();
      classInfo.parent = parentName;
      this.symbolTable.put(this.currentClassName, classInfo);
      
      n.f5.accept(this, argu); 
      n.f6.accept(this, argu); 

      this.currentClassName = null; 
      return null;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      String type = (String) n.f0.accept(this, argu);
      String name = (String) n.f1.accept(this, argu);

      if (currentMethodName != null) {
         
         MethodInfo methodInfo = symbolTable.get(currentClassName).methods.get(currentMethodName);
         if(methodInfo.localVariables.containsKey(name))
         {
            System.out.println("Type error");
            System.exit(0);
         }
         methodInfo.addLocalVariable(name, type);
      } else if (currentClassName != null) {
         
         ClassInfo classInfo = symbolTable.get(currentClassName);
         classInfo.addField(name, type);
      }
      return null;
   }


    public R visit(MethodDeclaration n, A argu) {
        
        String returnType = (String) n.f1.accept(this, argu);
        String methodName = n.f2.f0.tokenImage;

      
        MethodInfo newMethodInfo = new MethodInfo();
        newMethodInfo.returnType = returnType;

        ClassInfo currentClassInfo = this.symbolTable.get(this.currentClassName);

        
        if (currentClassInfo.methods.containsKey(methodName)) {
            System.out.println("Type error");
            System.exit(0);
        }

        
        currentClassInfo.methods.put(methodName, newMethodInfo);
        this.currentMethodName = methodName;

        
        n.f4.accept(this, argu);

     
        String parentClassName = currentClassInfo.parent;
        if (parentClassName != null) {
            MethodInfo parentMethodInfo = lookupMethodInHierarchy(parentClassName, methodName);

            
            if (parentMethodInfo != null) {
             
                if (!parentMethodInfo.returnType.equals(newMethodInfo.returnType)) {
                    System.out.println("Type error");
                    System.exit(0);
                }

                if (parentMethodInfo.parameters.size() != newMethodInfo.parameters.size()) {
                    System.out.println("Type error");
                    System.exit(0);
                }

                
                Iterator<String> parentParamTypes = parentMethodInfo.parameters.values().iterator();
                Iterator<String> currentParamTypes = newMethodInfo.parameters.values().iterator();
                while (parentParamTypes.hasNext()) {
                    if (!parentParamTypes.next().equals(currentParamTypes.next())) {
                        System.out.println("Type error");
                        System.exit(0);
                    }
                }
            }
        }
        
 
        n.f7.accept(this, argu);

        
        this.currentMethodName = null;
        return null;
    }
   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return null;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      String type = (String) n.f0.accept(this, argu);
      String name = (String) n.f1.accept(this, argu);

      MethodInfo methodInfo = symbolTable.get(currentClassName).methods.get(currentMethodName);
      methodInfo.addParameter(name, type);
      return null;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      n.f1.accept(this, argu);
      return null;
   }

   /**
    * f0 -> ArrayType()
    * | BooleanType()
    * | IntegerType()
    * | Identifier()
    * | LambdaType()
    */
   public R visit(Type n, A argu) {
      
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      return (R)"int[]";
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      return (R)"boolean";
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      return (R)"int";
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      String inputType = (String) n.f2.accept(this, argu);
      String outputType = (String) n.f4.accept(this, argu);
      return (R)("Function<" + inputType + "," + outputType + ">");
   }

    /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      
      String var_name = n.f0.tokenImage;
      return (R)n.f0.tokenImage;
   }

  

   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   public R visit(Expression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   public R visit(AndExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(OrExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(neqExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(AddExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(DivExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   public R visit(MessageSend n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }
}