//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import java.text.ParseException;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   Hashtable<String, String> var_types=new Hashtable<>();
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( DeclStatement() )*
    * f1 -> ( Statement() )*
    * f2 -> PrintStatment()
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntDecl()
    *       | BoolDecl()
    */
   public R visit(DeclStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INT>
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(IntDecl n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R name=n.f1.accept(this, argu);
      // System.out.println(name.toString());
      var_types.put(name.toString(),"int");
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <BOOL>
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(BoolDecl n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      R name=n.f1.accept(this, argu);
      var_types.put(name.toString(),"bool");
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <PRINT>
    * f1 -> Identifier()
    */
   public R visit(PrintStatment n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> AssignmentStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      R name=n.f0.accept(this, argu);
      if(!var_types.containsKey(name.toString()))  { System.out.println("does not type check\n"); System.exit(0); }
      n.f1.accept(this, argu);
      R _ret_type=n.f2.accept(this, argu);
      if(!_ret_type.equals(var_types.get(name.toString())))   { System.out.println("does not type check\n"); System.exit(0); }
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PlusExpression()
    *       | MinusExpression()
    *       | GTExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu) {
      // R _ret=null;
      // n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      // return _ret;
      R _ret=(R) "int";
      R _ret1=n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R _ret2=n.f2.accept(this, argu);
      if(!_ret1.equals("int") || !_ret2.equals("int")) { System.out.println("does not type check\n"); System.exit(0); }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      // R _ret=null;
      // n.f0.accept(this, argu);
      // n.f1.accept(this, argu);
      // n.f2.accept(this, argu);
      // return _ret;
      R _ret=(R) "int";
      R _ret1=n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R _ret2=n.f2.accept(this, argu);
      if(!_ret1.equals("int") || !_ret2.equals("int")) { System.out.println("does not type check\n"); System.exit(0); }

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> ">"
    * f2 -> PrimaryExpression()
    */
   public R visit(GTExpression n, A argu) {
      R _ret=(R) "bool";
      R _ret1=n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R _ret2=n.f2.accept(this, argu);
      if(!_ret1.equals("int") || !_ret2.equals("int")) { System.out.println("does not type check\n"); System.exit(0); }

      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | Identifier()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=n.f0.accept(this, argu);
      // System.out.println(_ret);
      if(!_ret.equals("int")) 
      {
         if(var_types.containsKey(_ret))   _ret=(R)var_types.get(_ret);
         else  { System.out.println("does not type check\n"); System.exit(0); }
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      // System.out.println("integer bro");
      n.f0.accept(this, argu);
      R _ret=(R)"int";
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      // System.out.println("id bro");

      n.f0.accept(this, argu);
      R _ret=(R)n.f0;
      return _ret;
   }

}
