//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;


public class GJDepthFirst<R,A> implements GJVisitor<R,A> {


   private int tempCounter = 200; 
   private String getNewTemp() {
      return "TEMP " + (tempCounter++);
   }


   public R visit(NodeList n, A argu) {
      if (n.size() < 1) return null;
      StringBuilder sb = new StringBuilder();
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         Object result = e.nextElement().accept(this, argu);
         if (result != null) {
            sb.append(result.toString());
         }
      }
      return (R) sb.toString();
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         if (n.size() < 1) return null;
         StringBuilder sb = new StringBuilder();
         for (Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            Object result = e.nextElement().accept(this, argu);
            if (result != null) {
               sb.append(result.toString());
            }
         }
         return (R) sb.toString();
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      if (n.size() < 1) return null;
      StringBuilder sb = new StringBuilder();
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         Object result = e.nextElement().accept(this, argu);
         if (result != null) {
            sb.append(result.toString());
         }
      }
      return (R) sb.toString();
   }

   public R visit(NodeToken n, A argu) { return (R) n.tokenImage; }


   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      String mainStmts = (String) n.f1.accept(this, argu);
      String procedures = (String) n.f3.accept(this, argu);
      
      String mainCode = "MAIN\n" + (mainStmts != null ? mainStmts : "") + "END\n";
      String procCode = (procedures != null ? procedures : "");

      return (R) (mainCode + procCode);
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      if (!n.f0.present()) {
         return null;
      }

      StringBuilder sb = new StringBuilder();
      for (Node node : n.f0.nodes) {
         NodeSequence seq = (NodeSequence) node;
         NodeOptional labelOpt = (NodeOptional) seq.elementAt(0);
         Stmt stmt = (Stmt) seq.elementAt(1);

         if (labelOpt.present()) {
            TranslationResult labelRes = (TranslationResult) labelOpt.node.accept(this, argu);
            sb.append(labelRes.resultIdentifier).append("\n");
         }

         String stmtCode = (String) stmt.accept(this, argu);
         sb.append(stmtCode);
      }

      return (R) sb.toString();
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      TranslationResult labelRes = (TranslationResult) n.f0.accept(this, argu);
      TranslationResult intLitRes = (TranslationResult) n.f2.accept(this, argu);
      
      TranslationResult bodyRes = (TranslationResult) n.f4.accept(this, argu);
      String procedureBody = "BEGIN\n" + bodyRes.code + "RETURN " + bodyRes.resultIdentifier + "\nEND";
      
      String procedureCode = labelRes.resultIdentifier + " [" + intLitRes.resultIdentifier + "]\n" + procedureBody + "\n";
      return (R) procedureCode;
   }

   /**
    * f0 -> NoOpStmt()
    * | ErrorStmt()
    * | CJumpStmt()
    * | JumpStmt()
    * | HStoreStmt()
    * | HLoadStmt()
    * | MoveStmt()
    * | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      return (R) "NOOP\n";
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      return (R) "ERROR\n";
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Exp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      TranslationResult condRes = (TranslationResult) n.f1.accept(this, argu);
      TranslationResult labelRes = (TranslationResult) n.f2.accept(this, argu);
      
      String precedingCode = condRes.code;
      String conditionIdentifier = condRes.resultIdentifier;
      
      if (!conditionIdentifier.startsWith("TEMP")) {
          String newTemp = getNewTemp();
          precedingCode += "MOVE " + newTemp + " " + conditionIdentifier + "\n";
          conditionIdentifier = newTemp;
      }

      String code = precedingCode + "CJUMP " + conditionIdentifier + " " + labelRes.resultIdentifier + "\n";
      return (R) code;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      TranslationResult labelRes = (TranslationResult) n.f1.accept(this, argu);
      String code = "JUMP " + labelRes.resultIdentifier + "\n";
      return (R) code;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Exp()
    * f2 -> IntegerLiteral()
    * f3 -> Exp()
    */
   public R visit(HStoreStmt n, A argu) {
      TranslationResult addrRes = (TranslationResult) n.f1.accept(this, argu);
      TranslationResult offsetRes = (TranslationResult) n.f2.accept(this, argu);
      TranslationResult valRes = (TranslationResult) n.f3.accept(this, argu);
      
      StringBuilder precedingCode = new StringBuilder();
      precedingCode.append(addrRes.code);
      precedingCode.append(valRes.code);
      
      String addressIdentifier = addrRes.resultIdentifier;
      String valueIdentifier = valRes.resultIdentifier;
      
      if (!addressIdentifier.startsWith("TEMP")) {
          String newTemp = getNewTemp();
          precedingCode.append("MOVE ").append(newTemp).append(" ").append(addressIdentifier).append("\n");
          addressIdentifier = newTemp;
      }
      
      if (!valueIdentifier.startsWith("TEMP")) {
          String newTemp = getNewTemp();
          precedingCode.append("MOVE ").append(newTemp).append(" ").append(valueIdentifier).append("\n");
          valueIdentifier = newTemp;
      }
      
      String hstoreCode = "HSTORE " + addressIdentifier + " " + offsetRes.resultIdentifier + " " + valueIdentifier + "\n";
      return (R) (precedingCode.toString() + hstoreCode);
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Exp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      TranslationResult destRes = (TranslationResult) n.f1.accept(this, argu);
      TranslationResult srcAddrRes = (TranslationResult) n.f2.accept(this, argu);
      TranslationResult offsetRes = (TranslationResult) n.f3.accept(this, argu);

      StringBuilder precedingCode = new StringBuilder();
      precedingCode.append(srcAddrRes.code);
      String addressIdentifier = srcAddrRes.resultIdentifier;

      if (!addressIdentifier.startsWith("TEMP")) {
          String newTemp = getNewTemp();
          precedingCode.append("MOVE ").append(newTemp).append(" ").append(addressIdentifier).append("\n");
          addressIdentifier = newTemp;
      }
      
      String hloadCode = "HLOAD " + destRes.resultIdentifier + " " + addressIdentifier + " " + offsetRes.resultIdentifier + "\n";
      return (R) (precedingCode.toString() + hloadCode);
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      TranslationResult destRes = (TranslationResult) n.f1.accept(this, argu);
      TranslationResult expRes = (TranslationResult) n.f2.accept(this, argu);
      
      String code = expRes.code + "MOVE " + destRes.resultIdentifier + " " + expRes.resultIdentifier + "\n";
      return (R) code;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> Exp()
    */
   public R visit(PrintStmt n, A argu) {
      TranslationResult expRes = (TranslationResult) n.f1.accept(this, argu);
      String code = expRes.code + "PRINT " + expRes.resultIdentifier + "\n";
      return (R) code;
   }

   /**
    * f0 -> StmtExp()
    * | Call()
    * | HAllocate()
    * | BinOp()
    * | Temp()
    * | IntegerLiteral()
    * | Label()
    */
   public R visit(Exp n, A argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> Exp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      String stmts = (String) n.f1.accept(this, argu);
      TranslationResult retExpRes = (TranslationResult) n.f3.accept(this, argu);

      String precedingCode = (stmts != null ? stmts : "") + retExpRes.code;
      String resultId = retExpRes.resultIdentifier;
      
      return (R) new TranslationResult(precedingCode, resultId);
   }

   /**
    * f0 -> "CALL"
    * f1 -> Exp()
    * f2 -> "("
    * f3 -> ( Exp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      TranslationResult funcRes = (TranslationResult) n.f1.accept(this, argu);
      
      StringBuilder precedingCode = new StringBuilder();
      precedingCode.append(funcRes.code);

      String funcIdentifier = funcRes.resultIdentifier;
      if (!funcIdentifier.startsWith("TEMP") && !Character.isLetter(funcIdentifier.charAt(0))) {
          String newTemp = getNewTemp();
          precedingCode.append("MOVE ").append(newTemp).append(" ").append(funcIdentifier).append("\n");
          funcIdentifier = newTemp;
      }

      StringBuilder argsList = new StringBuilder();
      if (n.f3.present()) {
         for (Node node : n.f3.nodes) {
            TranslationResult argRes = (TranslationResult) node.accept(this, argu);
            precedingCode.append(argRes.code);
            String argIdentifier = argRes.resultIdentifier;

            if (!argIdentifier.startsWith("TEMP")) {
                String newTemp = getNewTemp();
                precedingCode.append("MOVE ").append(newTemp).append(" ").append(argIdentifier).append("\n");
                argIdentifier = newTemp;
            }
            argsList.append(argIdentifier).append(" ");
         }
      }
      
      String resultTemp = getNewTemp();
      String callStmt = "MOVE " + resultTemp + " CALL " + funcIdentifier + " ( " + argsList.toString() + ")\n";
      
      return (R) new TranslationResult(precedingCode.toString() + callStmt, resultTemp);
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> Exp()
    */
   public R visit(HAllocate n, A argu) {
      TranslationResult sizeRes = (TranslationResult) n.f1.accept(this, argu);
      String newTemp = getNewTemp();
      
      String code = sizeRes.code + "MOVE " + newTemp + " HALLOCATE " + sizeRes.resultIdentifier + "\n";
      return (R) new TranslationResult(code, newTemp);
   }

   /**
    * f0 -> Operator()
    * f1 -> Exp()
    * f2 -> Exp()
    */
   public R visit(BinOp n, A argu) {
      String op = (String) n.f0.accept(this, argu);
      TranslationResult op1Res = (TranslationResult) n.f1.accept(this, argu);
      TranslationResult op2Res = (TranslationResult) n.f2.accept(this, argu);
      
      StringBuilder precedingCode = new StringBuilder();
      precedingCode.append(op1Res.code);
      precedingCode.append(op2Res.code);
      
      String operand1 = op1Res.resultIdentifier;
      if (!operand1.startsWith("TEMP")) {
          String newTemp = getNewTemp();
          precedingCode.append("MOVE ").append(newTemp).append(" ").append(operand1).append("\n");
          operand1 = newTemp;
      }

      String resultTemp = getNewTemp();
      String binOpStmt = "MOVE " + resultTemp + " " + op + " " + operand1 + " " + op2Res.resultIdentifier + "\n";

      return (R) new TranslationResult(precedingCode.toString() + binOpStmt, resultTemp);
   }

   /**
    * f0 -> "LE"
    * | "NE"
    * | "PLUS"
    * | "MINUS"
    * | "TIMES"
    * | "DIV"
    */
   public R visit(Operator n, A argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      String tempNum = (String) n.f1.f0.accept(this, argu);
      String tempStr = "TEMP " + tempNum;
      return (R) new TranslationResult("", tempStr);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      String intStr = (String) n.f0.accept(this, argu);
      return (R) new TranslationResult("", intStr);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      String labelStr = (String) n.f0.accept(this, argu);
      return (R) new TranslationResult("", labelStr);
   }

}